@echo off
setlocal

:: Update Arduino CLI and board packages
@REM .\arduino-cli core update-index
@REM .\arduino-cli core upgrade

set "product_name=Thor's Arsenal"
set last_compiled_file=C:\Users\shann\AppData\Local\Arduino15\last_compiled.txt
set last_compiled=
if exist %last_compiled_file% (
    for /F "delims=" %%i in (%last_compiled_file%) do set last_compiled=%%i
)

set src_dir=src
set hardware_dir=C:\Users\shann\Dropbox\moog\Thors Arsenal\code\src
set fname=.\src\hardware\greenface\mbed_nano\0.0.0\boards.txt

:: Set the ARDUINO_SKETCHBOOK_DIR environment variable
set ARDUINO_SKETCHBOOK_DIR=%hardware_dir%

if not "%1"=="" (
   if "%1"=="Bonkulator" (
      set "product_name=BONKULATOR"
      set "product=1"
      set "target=1"
      set "out_dir=.\bonk_out"
      goto goforit
   ) else (   
      set "product_name=THORS_ARSENAL"
      set "product=2"
      set "target=2"
      set "out_dir=.\thors_out"
      goto goforit
   ) 
) 
:get_product_name
set /p "product=What's the target product? (enter 1 for Bonkulator, 2 for Thor's Arsenal) 'x' to exit: "
if "%product%"=="x" exit

if "%product%" NEQ "1" if "%product%" NEQ "2" goto get_product_name

if "%product%"=="1" (
   set "product_name=BONKULATOR"
   set "out_dir=.\bonk_out"
) else if "%product%"=="2" (
   set "product_name=THORS_ARSENAL"
   set "out_dir=.\thors_out"
)

:entry
set /p "target=What's the target hardware? (enter 1 for Arduino, 2 for Greenface) 'x' to exit: "

if "%target%"=="x" exit

if "%target%" NEQ "1" if "%target%" NEQ "2" goto entry

:goforit
if "%target%"=="1" (
   set "target_name=Arduino"
) else if "%target%"=="2" (
   set "target_name=Greenface"
)

echo %out_dir% > out_dir.txt

echo.
echo.
echo Make %product_name% from source dir: %src_dir%, target: %target_name%

echo /* Do not edit this file. It is generated by make.bat. */ > .\%src_dir%\config.h
echo #ifndef CONFIG_H >> .\%src_dir%\config.h
echo #define CONFIG_H >> .\%src_dir%\config.h
echo #define %product_name% >> .\%src_dir%\config.h

if "%target%"=="1" (
   echo #define WIFI_INSTALLED >> .\%src_dir%\config.h
   echo #endif >> .\%src_dir%\config.h
   .\arduino-cli compile -b arduino:mbed_nano:nanorp2040connect --output-dir %out_dir% --libraries .\%src_dir%\libraries %src_dir%
) else if "%target%"=="2" (
   echo #define WIFI_NOT_INSTALLED >> .\%src_dir%\config.h
   echo #endif >> .\%src_dir%\config.h
   echo Last compiled product: %last_compiled%.
   echo Current product name: %product_name%.
   
   if "%last_compiled%" NEQ "%product_name%" (
       echo Cleaning cache!
       powershell -Command "if (Test-Path '%fname%') { (Get-Item '%fname%').LastWriteTime = Get-Date }"
       .\arduino-cli config set directories.user "C:\Users\shann\Dropbox\moog\Thors Arsenal\code\src"
       echo %product_name% > last_compiled.txt
   ) else (
       echo No need to clean cache.
   )
      
   .\arduino-cli compile -b greenface:mbed_nano:greenface_rp2040 --output-dir %out_dir% --libraries .\%src_dir%\libraries %src_dir% 
)

if errorlevel 1 (
   if "%~1"=="" echo Compiler Error: %errorlevel%
	powershell -command "[console]::beep()"
	powershell -command "[console]::beep()"
	powershell -command "[console]::beep()"
	powershell -command "[console]::beep()"
   set /p "exitkey=Press any key to continue..."
   exit /b %errorlevel%
)

echo %product_name%>%last_compiled_file%

@REM setx GREENFACE_COMPILE "%product_name%"
@REM setx ARDUINO_DIRECTORIES_USER ""
endlocal
powershell -command "[console]::beep()"
powershell -command "[console]::beep()"

exit /b 0