#!/bin/zsh

# ./bin/arduino-cli compile -b arduino:mbed_nano:nanorp2040connect --output-dir ./out --libraries ./Bonkulator/libraries Bonkulator

read -p "What's the target product? (enter 1 for Bonkulator, 2 for Thor's Arsenal) 'x' to exit: " product
if [ "$product" == "x" ]; then
  exit
fi

while [ "$product" != "1" ] && [ "$product" != "2" ]; do
  read -p "Invalid input. What's the target product? (enter 1 for Bonkulator, 2 for Thor's Arsenal) 'x' to exit: " product
  if [ "$product" == "x" ]; then
    exit
  fi
done

if [ "$product" == "1" ]; then
  product_name="BONKULATOR"
elif [ "$product" == "2" ]; then
  product_name="THORS_ARSENAL"
fi

while true; do
  read -p "What's the target hardware? (enter 1 for Arduino, 2 for Greenface) 'x' to exit: " target
  if [ "$target" == "x" ]; then
    exit
  fi

  if [ "$target" == "1" ] || [ "$target" == "2" ]; then
    break
  fi
done

if [ "$target" == "1" ]; then
  target_name="Arduino"
elif [ "$target" == "2" ]; then
  target_name="Greenface"
fi

echo
echo
echo "Make $product_name from source dir: $src_dir, target: $target_name"

echo "/* Do not edit this file. It is generated by make.sh. */" > ./$src_dir/config.h
echo "#define $product_name" >> ./$src_dir/config.h

if [ "$target" == "1" ]; then
  echo "#define WIFI_INSTALLED" >> ./$src_dir/config.h
  ./arduino-cli compile -b arduino:mbed_nano:nanorp2040connect --output-dir ./out --libraries ./$src_dir/libraries $src_dir
elif [ "$target" == "2" ]; then
  echo "#define WIFI_NOT_INSTALLED" >> ./$src_dir/config.h
  ./arduino-cli compile -b greenface:mbed_nano:greenface_rp2040 --output-dir ./out --libraries ./$src_dir/libraries $src_dir
fi